<?php
$data = array (
  'domain' => 'http://ekanpou',
  'url' => 'http://ekanpou/',
  'shop_name' => 'Ekanpu.shop',
  'shop_title' => 'Ekanpu.shop',
  'shop_desc' => 'Ekanpu.shop',
  'shop_keywords' => 'Ekanpu.shop',
  'country' => '日本国',
  'province' => '海外',
  'city' => 'その他',
  'address' => '',
  'qq' => '',
  'ww' => '',
  'ym' => '',
  'msn' => '',
  'email' => '12345@qq.com',
  'phone' => '13354638533',
  'icp' => '15002903',
  'version' => 'v2.5.2',
  'release' => '20180409',
  'language' => 'zh_cn',
  'php_ver' => '5.6.9',
  'mysql_ver' => '5.7.26',
  'charset' => 'utf-8',
);
?>